# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xBJJGFWi4GQxMG-MfJjSoqXepU0rEs-R
"""

nome  = ('felipe')
nomex  = input("digite seu nome ")
sobrenome = ('zarcky')
sobrenomex = input("digite seu nome ")
if nome == nomex and sobrenome == sobrenomex:
 print(nome,sobrenome)
else:
 print("não é pra vc")

for numero in range (10):
 print(numero)